### ISSUE TITLE
Memory Leak due to ThreadSafeBuffer not cleared?

### ISSUE THREAD

**Issue by vangoft** [ultraware/DelphiGrpc#2]
I ran across a phenomenon, where my delphi client application runs out of memory, after a certain amount of requests done by the gRPC client (in my case after around 2000 requests). You can reproduce the error by simply running a lot of requests in your DEMOs, after a few requests you can already see, that the memory usage is going up in Taskmanager.

eurekaLogs says the error is produced at "TThreadSafeBuffer"-"Create"  when it sets the length of the buffer, SetLength(...), in Grijjy.HTTP  (not http2)

**Comment by andremussche** [comment]
Hi @acces90, do you have a stracktrace (from eurekalog) for me?
