### ISSUE TITLE
TThreadSafeBuffer

### ISSUE THREAD

**Issue by 123maxj** [ultraware/DelphiGrpc#4]
I found two bugs in the TThreadSaveBuf class and the write and read method. The Write method write(const ABytes: TBytes) fails when ABytes = nil. I solved the problem by the following code change: if ABytes<>nil then
                                                                                                            Write(@ABytes[0], Length(ABytes))
                                                                                                        else
                                                                                                           FSize := 0;
The second bug is in the overloaded Read(const ABuffer: Pointer; var ALength: NativeInt) function.  Error clearing read data in buffer.
I solved the problem by replacing line Move(FBuffer[Size], FBuffer[0], FSize - ALength); 
with line Move(FBuffer[ALength], FBuffer[0], FSize - ALength);.

**Comment by andremussche** [comment]
Thanks @123maxj , can you make a pull request with the changes for me?
