### ISSUE TITLE
Sourcecode or updated executable for ProtoBufGenerator availabe?

### ISSUE THREAD

**Issue by georgkeller** [ultraware/DelphiGrpc#5]
The available ProtoBufGenerator executable does not produce the correct code for the latest version of the library (and not the same code as the one included in the examples). Could you make an updated version of the ProtoBufGenerator executeable available? Or the source code for it?

**Comment by andremussche** [comment]
I added the sourcecode for it in de special sub branch: https://github.com/ultraware/DelphiGrpc/tree/master-Generator
(not sure if it still works though...)

**Comment by georgkeller** [comment]
Thank you very much, I will try it out.
